---
driver:
  name: terraform
  root_module_directory: test/fixtures/default

provisioner:
  name: terraform

platforms:
  - name: test

verifier:
  name: terraform
  format: documentation
  systems:
    - name: remote
      controls:
        - remote
      show_progress: true
      backend: ssh
      hosts_output: nginx_ip
      user: ubuntu
      key_files:
        - test/fixtures/default/keys/key
    - name: aws
      controls:
        - aws
      backend: aws
      show_progress: true
    - name: local
      controls:
        - local
      backend: local
      show_progress: true

suites:
  - name: default
